import { ScrollArea } from "@/components/ui/scroll-area";
import { ClerkProvider } from "@clerk/nextjs";
import { Scrollbar } from "@radix-ui/react-scroll-area";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppinsFont = Poppins({
	weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
	subsets: ["latin"],
	style: ["normal", "italic"],
});

export const metadata: Metadata = {
	title: "TixPulse",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider dynamic>
			<html lang="en" suppressHydrationWarning>
				<body
					className={`${poppinsFont.className} antialiased bg-background text-foreground`}
				>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<ScrollArea className="h-screen">
							<main>{children}</main>

							<Scrollbar />
						</ScrollArea>
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
