import AppSidebar from "@/components/AppSidebar";
import Navbar from "@/components/Navbar";
import { ScrollArea } from "@/components/ui/scroll-area";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { Scrollbar } from "@radix-ui/react-scroll-area";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
	title: "TixPulse",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className={`bg-background text-foreground`}>
			<Toaster />
			<SidebarProvider>
				<AppSidebar />

				<SidebarInset>
					<ScrollArea className="h-screen">
						<nav className="relative">
							<Navbar />
						</nav>
						<main className="p-2 md:p-3">{children}</main>

						<Scrollbar />
					</ScrollArea>
				</SidebarInset>
			</SidebarProvider>
		</div>
	);
}
