import AppSidebar from "@/components/AppSidebar";
import Navbar from "@/components/Navbar";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
	SidebarInset,
	SidebarProvider,
	SidebarTrigger,
} from "@/components/ui/sidebar";
import { Scrollbar } from "@radix-ui/react-scroll-area";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import {
	Tooltip,
	TooltipContent,
	TooltipTrigger,
} from "@/components/ui/tooltip";

const poppinsFont = Poppins({
	weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
	subsets: ["latin"],
	style: ["normal", "italic"],
});

export const metadata: Metadata = {
	title: "TixPulse",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div
			className={`${poppinsFont.className} antialiased bg-background text-foreground`}
		>
			<SidebarProvider>
				<AppSidebar />

				<SidebarInset>
					<ScrollArea className="h-screen">
						<nav className="relative">
							<Navbar />
						</nav>
						<main className="p-2 md:p-3">{children}</main>

						<Scrollbar />
					</ScrollArea>
				</SidebarInset>
			</SidebarProvider>
		</div>
	);
}
